#!/usr/bin/env bash
set -euo pipefail

##########################################################
# Code generated by protoc-gen-list-messages. DO NOT EDIT.
##########################################################

printf 'The messages defined in the provided proto file are:\n'
printf 'echo.v1.EchoRequest\n'
printf 'echo.v1.EchoResponse\n'
