# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http/v1/http.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='http/v1/http.proto',
  package='proto.http.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x12http/v1/http.proto\x12\rproto.http.v1\x1a\x1cgoogle/api/annotations.proto\" \n\x10GetRecordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"P\n\x11GetRecordResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x03(\t2\x81\x01\n\x0bHttpService\x12r\n\tGetRecord\x12\x1f.proto.http.v1.GetRecordRequest\x1a .proto.http.v1.GetRecordResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/http/v1/get_record/{name}B>Z<github.com/opensourcecorp/workshops/protobuf-grpc/pb/http/v1b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_GETRECORDREQUEST = _descriptor.Descriptor(
  name='GetRecordRequest',
  full_name='proto.http.v1.GetRecordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.http.v1.GetRecordRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=99,
)


_GETRECORDRESPONSE = _descriptor.Descriptor(
  name='GetRecordResponse',
  full_name='proto.http.v1.GetRecordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.http.v1.GetRecordResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.http.v1.GetRecordResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='proto.http.v1.GetRecordResponse.birthday', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='proto.http.v1.GetRecordResponse.details', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['GetRecordRequest'] = _GETRECORDREQUEST
DESCRIPTOR.message_types_by_name['GetRecordResponse'] = _GETRECORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRecordRequest = _reflection.GeneratedProtocolMessageType('GetRecordRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDREQUEST,
  __module__ = 'http.v1.http_pb2'
  # @@protoc_insertion_point(class_scope:proto.http.v1.GetRecordRequest)
  ))
_sym_db.RegisterMessage(GetRecordRequest)

GetRecordResponse = _reflection.GeneratedProtocolMessageType('GetRecordResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRECORDRESPONSE,
  __module__ = 'http.v1.http_pb2'
  # @@protoc_insertion_point(class_scope:proto.http.v1.GetRecordResponse)
  ))
_sym_db.RegisterMessage(GetRecordResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z<github.com/opensourcecorp/workshops/protobuf-grpc/pb/http/v1'))

_HTTPSERVICE = _descriptor.ServiceDescriptor(
  name='HttpService',
  full_name='proto.http.v1.HttpService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=184,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecord',
    full_name='proto.http.v1.HttpService.GetRecord',
    index=0,
    containing_service=None,
    input_type=_GETRECORDREQUEST,
    output_type=_GETRECORDRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\034\022\032/http/v1/get_record/{name}')),
  ),
])
_sym_db.RegisterServiceDescriptor(_HTTPSERVICE)

DESCRIPTOR.services_by_name['HttpService'] = _HTTPSERVICE

# @@protoc_insertion_point(module_scope)
