FROM golang:1.21

WORKDIR /root

COPY go.mod /root/go.mod
# COPY go.sum /root/go.sum
COPY main.go /root/main.go
RUN go build -o /root/app ./...

EXPOSE 8080

HEALTHCHECK --start-period=1s --interval=5s --timeout=1s CMD curl -fsSL http://127.0.0.1:8080/health || exit 1
CMD ["/root/app"]
