# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import employees_pb2 as employees_dot_v1_dot_employees__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class EmployeesServiceStub(object):
  """Service that shows a few ways to work with protobufs and gRPC
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetEmployee = channel.unary_unary(
        '/employees.v1.EmployeesService/GetEmployee',
        request_serializer=employees_dot_v1_dot_employees__pb2.GetEmployeeRequest.SerializeToString,
        response_deserializer=employees_dot_v1_dot_employees__pb2.GetEmployeeResponse.FromString,
        )
    self.ListEmployees = channel.unary_unary(
        '/employees.v1.EmployeesService/ListEmployees',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=employees_dot_v1_dot_employees__pb2.ListEmployeesResponse.FromString,
        )


class EmployeesServiceServicer(object):
  """Service that shows a few ways to work with protobufs and gRPC
  """

  def GetEmployee(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListEmployees(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EmployeesServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetEmployee': grpc.unary_unary_rpc_method_handler(
          servicer.GetEmployee,
          request_deserializer=employees_dot_v1_dot_employees__pb2.GetEmployeeRequest.FromString,
          response_serializer=employees_dot_v1_dot_employees__pb2.GetEmployeeResponse.SerializeToString,
      ),
      'ListEmployees': grpc.unary_unary_rpc_method_handler(
          servicer.ListEmployees,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=employees_dot_v1_dot_employees__pb2.ListEmployeesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'employees.v1.EmployeesService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
