# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employees/v1/employees.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65mployees/v1/employees.proto\x12\x0c\x65mployees.v1\x1a\x1cgoogle/api/annotations.proto\" \n\x10GetRecordRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"?\n\x11GetRecordResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\t2\x89\x01\n\x10\x45mployeesService\x12u\n\tGetRecord\x12\x1e.employees.v1.GetRecordRequest\x1a\x1f.employees.v1.GetRecordResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/employees/v1/get_record/{name}BCZAgithub.com/opensourcecorp/workshops/protobuf-grpc/pb/employees/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employees.v1.employees_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZAgithub.com/opensourcecorp/workshops/protobuf-grpc/pb/employees/v1'
  _EMPLOYEESSERVICE.methods_by_name['GetRecord']._options = None
  _EMPLOYEESSERVICE.methods_by_name['GetRecord']._serialized_options = b'\202\323\344\223\002!\022\037/employees/v1/get_record/{name}'
  _GETRECORDREQUEST._serialized_start=76
  _GETRECORDREQUEST._serialized_end=108
  _GETRECORDRESPONSE._serialized_start=110
  _GETRECORDRESPONSE._serialized_end=173
  _EMPLOYEESSERVICE._serialized_start=176
  _EMPLOYEESSERVICE._serialized_end=313
# @@protoc_insertion_point(module_scope)
