#!/usr/bin/env bash
set -euo pipefail

#################################################
# Code generated by protoc-gen-bash. DO NOT EDIT.
#
# source file: echo/v1/echo.proto
#################################################

printf 'The messages defined in the provided proto file(s) are:\n'

printf '
  echo.v1.EchoRequest (fields: msg:string)
  echo.v1.EchoResponse (fields: msg:string)
'
