# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo/v1/echo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x63ho/v1/echo.proto\x12\x07\x65\x63ho.v1\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2B\n\x0b\x45\x63hoService\x12\x33\n\x04\x45\x63ho\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponseB>Z<github.com/opensourcecorp/workshops/protobuf-grpc/pb/echo/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo.v1.echo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/opensourcecorp/workshops/protobuf-grpc/pb/echo/v1'
  _ECHOREQUEST._serialized_start=31
  _ECHOREQUEST._serialized_end=57
  _ECHORESPONSE._serialized_start=59
  _ECHORESPONSE._serialized_end=86
  _ECHOSERVICE._serialized_start=88
  _ECHOSERVICE._serialized_end=154
# @@protoc_insertion_point(module_scope)
