# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import echo_pb2 as echo_dot_v1_dot_echo__pb2


class EchoServiceStub(object):
  """Service that shows a few ways to work with protobufs and gRPC
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Echo = channel.unary_unary(
        '/proto.echo.v1.EchoService/Echo',
        request_serializer=echo_dot_v1_dot_echo__pb2.EchoRequest.SerializeToString,
        response_deserializer=echo_dot_v1_dot_echo__pb2.EchoResponse.FromString,
        )


class EchoServiceServicer(object):
  """Service that shows a few ways to work with protobufs and gRPC
  """

  def Echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Echo': grpc.unary_unary_rpc_method_handler(
          servicer.Echo,
          request_deserializer=echo_dot_v1_dot_echo__pb2.EchoRequest.FromString,
          response_serializer=echo_dot_v1_dot_echo__pb2.EchoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.echo.v1.EchoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
