Vagrant.configure("2") do |config|
  box = "debian/bullseye64"

  cpus   = 2
  memory = 2048

  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = cpus
    vb.memory = memory
  end

  config.vm.provider "libvirt" do |lv|
    lv.cpus   = cpus
    lv.memory = memory
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "ws" do |ws|
    ws.vm.box = box

    ws.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"

    ws.vm.synced_folder ".", "/vagrant", disabled: true

    ws.vm.provision "file", source: "./scripts", destination: "/tmp/scripts"
    ws.vm.provision "file", source: "./services", destination: "/tmp/services"
    ws.vm.provision "file", source: "./instructions", destination: "/tmp/instructions"

    ws.vm.provision "shell",
      inline: <<-SCRIPT
        bash /tmp/scripts/init.sh
      SCRIPT
  end
end
