package main

import "google.golang.org/protobuf/compiler/protogen"

func main() {
	opts := protogen.Options{}
	opts.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if f.Generate {
				generateFile(gen, f)
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_list-messages.pb.sh"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("#!/usr/bin/env bash")
	g.P("set -euo pipefail")
	g.P()
	g.P("##########################################################")
	g.P("# Code generated by protoc-gen-list-messages. DO NOT EDIT.")
	g.P("##########################################################")
	g.P()
	g.P(`printf 'The messages defined in the provided proto file are:\n'`)

	for _, msg := range file.Messages {
		g.P(`printf '`, msg.Desc.FullName(), `\n'`)
	}
}
